config/routes.rb
Ctaridership::Application.routes.draw do

  root 'home#index'

  resources :datasets, controller: :ridership_datasets, only: :show do |dataset|

    resources :details, controller: :ridership_details, only: :show

    resources :routes, only: [:index, :show]
    resources :streets, only: [:index, :show]
  end

end

app/models/ridership_dataset.rb
class RidershipDataset < ActiveRecord::Base
  has_many :ridership_details

end

app/models/ridership_detail.rb
class RidershipDetail < ActiveRecord::Base
  belongs_to :ridership_dataset
  belongs_to :stop

  scope :by_route_number, ->(route_number) {joins(stop: {route_stops: :route}).where('routes.number' => route_number)}
  scope :by_route_id, ->(route_id) {joins(stop: :route_stops).where('route_stops.route_id' => route_id)}

end

app/models/ridership_route_detail.rb
class RidershipRouteDetail < ActiveRecord::Base
  belongs_to :ridership_dataset
  belongs_to :route
end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :route_stops

  has_many :stops, through: :route_stops

  STANDARD_CAPACITY = 82
  LARGE_CAPACITY = 125
end

app/models/route_stop.rb
class RouteStop < ActiveRecord::Base
  belongs_to :route
  belongs_to :stop

  scope :by_route, -> {select("id, route_id, count(*) as count").group("route_id")}
  scope :by_stop, -> {select("id, stop_id, count(*) as count").group("stop_id")}
  scope :descending, -> {order("count desc")}
  scope :ascending, -> {order("count asc")}

end

app/models/stop.rb
class Stop < ActiveRecord::Base
  has_many :route_stops

  has_many :routes, through: :route_stops 

  belongs_to :on_street, class_name: "Street", foreign_key: "on_street_id"
  belongs_to :cross_street, class_name: "Street", foreign_key: "cross_street_id"
end

app/models/street.rb
class Street < ActiveRecord::Base
  has_many :stops
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@datasets = RidershipDataset.all
  end
end

app/controllers/ridership_datasets_controller.rb
class RidershipDatasetsController < ApplicationController
  def show
  	@dataset = RidershipDataset.find(params[:id])

    @routes = Route.all.sort_by { |route| route.number }

    @route_ridership_details = route_ridership_details
  end

  private
  def route_ridership_details
    if params[:sort]

      details = 
        case params[:sort]
          when "route_number"
            RidershipRouteDetail.all.sort_by { |route_detail| route_detail.route.number}
          when "stops"
            RidershipRouteDetail.all.sort_by { |route_detail| route_detail.route.stops.count}
          when "boardings"
            RidershipRouteDetail.all.sort_by(&:total_boardings)
          when "alightings"
            RidershipRouteDetail.all.sort_by(&:total_alightings)
          when "median_boardings"
            RidershipRouteDetail.all.sort_by(&:median_boardings)
          when "median_alightings"
            RidershipRouteDetail.all.sort_by(&:median_alightings)
        end

      if params[:direction] == "desc"
        details.reverse!
      end
    else
      details = RidershipRouteDetail.all.sort_by { |route_detail| route_detail.total_boardings}.reverse
    end

    details
  end

end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  def index
    if params[:route_id]
      redirect_to dataset_route_path(params[:dataset_id], params[:route_id])
    end

  end

  def show
    @dataset = RidershipDataset.find(params[:dataset_id])
    @route = Route.find(params[:id])
    @details = ridership_details.page(params[:page]).per(50)

    @total_boardings = @details.inject(0) { |sum, n| sum += n.boardings }
    @avg_boardings = @total_boardings / @details.count

    @total_alightings = @details.inject(0) { |sum, n| sum += n.alightings }
    @avg_alightings = @total_alightings / @details.count
  end

  private
  def ridership_details
    details =  
      case params[:sort]
        when "boardings"
          @dataset.ridership_details.order("boardings #{params[:direction]}").by_route_id(params[:id])
        when "alightings"
          @dataset.ridership_details.order("alightings #{params[:direction]}").by_route_id(params[:id])
        else
          if params[:direction]
            @dataset.ridership_details.order("stop_id #{params[:direction]}").by_route_id(params[:id])
          else
            @dataset.ridership_details.by_route_id(params[:id])
          end
      end

    details
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = (column == params[:sort] && params[:direction] == "asc") ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ridership_dataset_helper.rb
module RidershipDatasetHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
  def details_for_chart
    @details.map{ |d| 
      {
        stop: d.stop.number, 
        boardings: d.boardings.to_s, 
        alightings: d.alightings.to_s,
        capacity_diff: (d.boardings - d.alightings).to_s
      }
    }.to_json
  end
end

app/views/home/index.html.haml
%h1 CTA Ridership Data

%ul.datasets
  - @datasets.each do |dataset|
    %li
      = link_to dataset.description, dataset_path(dataset)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ctaridership</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/ridership_datasets/show.html.haml
%h1= @dataset.description

%p
  Routes:
  = Route.count

%p
  Stop that appears on the most routes:
  = RouteStop.by_stop.descending.first.stop.on_street.name
  &
  = RouteStop.by_stop.descending.first.stop.cross_street.name
  Number of routes:
  = RouteStop.by_stop.descending.first.count

Select route:
= form_tag(dataset_routes_path(@dataset), method: :get) do |f|
  = select_tag :route_id, options_from_collection_for_select(@routes, :id, :number)

  = submit_tag 'Go'

%table
  %tr
    %th= sortable "route_number"
    %th= sortable "stops"
    %th= sortable "boardings"
    %th= sortable "alightings"
    %th= sortable "median_boardings"
    %th= sortable "median_alightings"

  - @route_ridership_details.each do |detail|
    %tr
      %td= link_to detail.route.number, dataset_route_path(@dataset.id, detail.route.id)
      %td= detail.route.stops.count
      %td= number_with_precision(detail.total_boardings, precision: 1)
      %td= number_with_precision(detail.total_alightings, precision: 1)
      %td= number_with_precision(detail.median_boardings, precision: 1)
      %td= number_with_precision(detail.median_alightings, precision: 1)

app/views/routes/show.html.haml
%h1 
  Route 
  = @route.number

#route-chart{data: {stops: details_for_chart}}

= paginate @details

%table
  %tr
    %th= sortable "stops"
    %th On Street
    %th Cross Street
    %th= sortable "boardings"
    %th= sortable "alightings"
    %th Location
    %th Stop found on other routes

  - @details.each do |detail|
    %tr
      %td= detail.stop.number
      %td= detail.stop.on_street.name
      %td= detail.stop.cross_street.name
      %td= number_with_precision(detail.boardings, precision: 1)
      %td= number_with_precision(detail.alightings, precision: 1)
      %td
        = link_to "Location", "http://maps.google.com/?q=#{detail.stop.longitude},#{detail.stop.latitude}", {target: "_blank"}
      %td
        - if (other_routes = detail.stop.routes.reject{|route| route.number == @route.number.to_s}).present?
          - other_routes.each do |route|
            = link_to route.number, dataset_route_path(@dataset, route.id)

= paginate @details

%p
  = link_to 'Back to dataset', dataset_path(@dataset)